# Author: Jacob Dawson

from googletrans import Translator, LANGCODES

translator = Translator()

# two corpi to translate to/from:
original = [
    "Alert, alert!",
    "DJ Crazy Times" "If you want parties to be making",
    "Have some noise",
    "Bratislava!",
    "All the women in the world",
    "Let me see your beautiful faces",
    "Oh, I've got an idea",
    "World peace!",
    "When the pleasure is a dream on a secret love",
    "And the people wanna make a fun",
    "We are losing control on a floor tonight",
    "Take your heart into a unicorn",
    "If the sky is not green, but the sky is blue",
    "Have a passion in a million way",
    "Touch it, make it twice, before I cry",
    "Heaven is a time today",
    "Put your hands up in the air",
    "All of the dream, how does it mean?",
    "When the rhythm is glad",
    "There is nothing to be sad",
    "Danger and dance",
    "Clapping the hands",
    "When we out in the space",
    "On the planet of the bass",
    "Life, it never die",
    "Women are my favorite guy",
    "Sex, I'm wanting more",
    "Tell the world, 'Stop the war'",
    "Boom, hear the bass go zoom",
    "Have a body, feel the groove",
    "Cyber system overload",
    "Everybody movement",
    "All of the dream, how does it mean?",
    "When the rhythm is glad",
    "There is nothing to be sad",
    "Danger and dance",
    "Clapping the hands",
    "When we out in the space",
    "On the planet of the bass",
    "Hello, are you at phone?",
    "Yes, it's true, yes, it's true",
    "Are you the girl of the love?",
    "Yes, I am a girl",
    "I love you and feel groove",
    "I love you too",
    "I want the sex on the phone",
    "I am so alone in the night",
    "Goodbye",
    "Goodbye",
    "And tonight, I will never die",
    "That is good to me as well as that",
]

manuallyTranslated = [
    "Alert, alert!",
    "DJ Crazy Times, If you want to throw a party",
    "Make some noise",
    "Bratislava!",
    "All the women in the world",
    "Let me see your beautiful faces",
    "Oh, I've got an idea",
    "World peace!",
    "When your secret love is like a dream",
    "And people are having fun",
    "We are losing control on the floor tonight",
    "You are as rare as a unicorn",
    "If the sky is not green, but the sky is blue",
    "Have great passion",
    "Touch me again, before I cry",
    "Heaven is when I'm with you",
    "Put your hands up in the air",
    "What do these dreams mean?",
    "When the rhythm is good",
    "There is no reason to be sad",
    "Danger and dance",
    "Clap your hands",
    "When we're out in space",
    "On the planet of the bass",
    "Life never dies",
    "I love women",
    "Sex, I want more",
    "Tell the world, 'Stop the war'",
    "Boom, hear the bass go zoom",
    "In your body, feel the groove",
    "Cyber system overload",
    "Everybody move",
    "What do these dreams mean?",
    "When the rhythm is good",
    "There is no reason to be sad",
    "Danger and dance",
    "Clap your hands",
    "When we're out in space",
    "On the planet of the bass",
    "Hello, are you there?",
    "Yes, I am",
    "Are you the girl of my dreams?",
    "Yes, I am a girl",
    "I love you and feel groovy",
    "I love you too",
    "I want phone sex",
    "I am so alone in the night",
    "Goodbye",
    "Goodbye",
    "And tonight, I will not die",
    "That is good with me as well",
]

# both 51 lines long
# print(len(original))
# print(len(manuallyTranslated))

original = [o.lower() for o in original]
manuallyTranslated = [m.lower() for m in manuallyTranslated]

languagesToTranslate = [
    "af",
    "sq",
    "am",
    "ar",
    "hy",
    "az",
    "eu",
    "be",
    "bn",
    "bs",
    "bg",
    "ca",
    "ceb",
    "ny",
    "zh-cn",
    "zh-tw",
    "co",
    "hr",
    "cs",
    "da",
    "nl",
    "en",
    "eo",
    "et",
    "tl",
    "fi",
    "fr",
    "fy",
    "gl",
    "ka",
    "de",
    "el",
    "gu",
    "ht",
    "ha",
    "haw",
    "he",
    "hi",
    "hmn",
    "hu",
    "is",
    "ig",
    "id",
    "ga",
    "it",
    "ja",
    "jw",
    "kn",
    "kk",
    "km",
    "ko",
    "ku",
    "ky",
    "lo",
    "la",
    "lv",
    "lt",
    "lb",
    "mk",
    "mg",
    "ms",
    "ml",
    "mt",
    "mi",
    "mr",
    "mn",
    "my",
    "ne",
    "no",
    "or",
    "ps",
    "fa",
    "pl",
    "pt",
    "pa",
    "ro",
    "ru",
    "sm",
    "gd",
    "sr",
    "st",
    "sn",
    "sd",
    "si",
    "sk",
    "sl",
    "so",
    "es",
    "su",
    "sw",
    "sv",
    "tg",
    "ta",
    "te",
    "th",
    "tr",
    "uk",
    "ur",
    "ug",
    "uz",
    "vi",
    "cy",
    "xh",
    "yi",
    "yo",
    "zu",
]


def compareToOriginal(language, inputTranslation):
    autoTranslated = [
        translator.translate(m, src="en", dest=language).text.lower()
        for m in inputTranslation
    ]
    # autoTranslated = [print(type(m)) for m in manuallyTranslated]
    numSame = 0
    i = 0
    for a in autoTranslated:
        retranslatedSentence = " ".join(
            [
                translator.translate(word, src=language, dest="en").text.lower()
                for word in a.split()
            ]
        )
        print(retranslatedSentence)
        if retranslatedSentence == original[i]:
            numSame += 1
        i += 1
    print("numSame:", numSame)


compareToOriginal('fr', manuallyTranslated)
print(list(LANGCODES.values()))
